name: Shuttle Deploy
concurrency:
  group: deploy
  cancel-in-progress: true
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: cargo-shuttle-env
    steps:
      - uses: shuttle-hq/deploy-action@v2
        with:
          shuttle-api-key: ${{ secrets.SHUTTLE_API_KEY }}
          project-id: ${{ secrets.SHUTTLE_PROJ_ID }}
          working-directory: "botsure"
          cargo-shuttle-version: "0.49.0"
          extra-args: --allow-dirty --debug
          secrets: |
            DISCORD_TOKEN = '${{ secrets.SECRETS_TOML_DISCORD_TOKEN }}'
            GUILD_ID = '${{ secrets.SECRETS_TOML_GUILD_ID }}'
            PERMISSIONS_INTEGER = '${{ secrets.SECRETS_TOML_PERMISSIONS_INTEGER }}'
            URL = '${{ secrets.SHUTTLE_URL }}'
            SSH_PRIVATE_KEY = ''
            SSH_PUBLIC_KEY = ''
            SSH_USERNAME = ''
            SSH_PORT = ''
            SSH_HOST = ''
            D6_WEBHOOK = ''
            D6_API = ''
